#!/bin/bash -x

scp $HOME/.ssh/id_rsa.pub root@$1:/tmp/
ssh root@$1 'cat /tmp/id_rsa.pub >> .ssh/authorized_keys;\
  chmod 700 .ssh/authorized_keys;\
  chmod 600 .ssh/authorized_keys;\
  chown root:root .ssh/;\
  chown root:root /root;\
  exit'
